---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: zephykus-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zephykus-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zephykus-clusterrole
subjects:
- kind: ServiceAccount
  name: default
  namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zephykus-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: zephykus
  template:
    metadata:
      labels:
        app: zephykus
    spec:
      containers:
      - image: timonback/zephykus
        imagePullPolicy: Always
        name: zephykus
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: zephykus-service
  namespace: default
  labels:
    app: zephykus-service
spec:
  selector:
    app: zephykus
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zephykus-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - path: /zephykus
        backend:
          serviceName: zephykus-service
          servicePort: 80
