name: Publish to Docker Hub
on:
  push:
    branches:
      - master
      - feature/github-action

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
    - name: Install Frontend dependencies
      run: npm install
      working-directory: ./frontend
    - name: Build Frontend
      run: |
        make build-webpack

  build-backend:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Go
      uses: actions/setup-go@v1.0.0
    - name: Build Backend
      run: |
        make build-go

  publish:
    needs: [build-frontend, build-backend]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2.1.0
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        DOCKERHUB_REPOSITORY: timonback/zephykus

    - name: Docker Hub Push
      uses: azure/docker-login@v1
      with:
        login-server: hub.docker.com
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - run: |
        version=$(cat ./VERSION)
        echo $VERSION
        docker build . -t timonback/zephykus:${{ github.sha }}
        docker push timonback/zephykus:${{ github.sha }}
